name: GitHub Container Registry Test

on:
  push:
    branches:
      - master

env:
  ImagePath:                    "ci-tools"
  ImageName:                    "image-scanner"
  RepositoryName:               "tomoyakitaura"

jobs:
  BuildAndShip:
    name: GitHub Container Regist
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and Ship
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/$RepositoryName/$ImageName:latest
          docker build $ImagePath/$ImageName --tag ghcr.io/$RepositoryName/$ImageName:$GITHUB_SHA --cache-from ghcr.io/$RepositoryName/$ImageName:latest
          docker push ghcr.io/$RepositoryName/$ImageName:$GITHUB_SHA
